language: r
dist: xenial
sudo: false
r:
  - oldrel
  - release
r_build_args: --no-manual
r_check_args: --no-manual
addons:
  apt:
    packages:
    - libglu1-mesa-dev
cache:
  packages: true
  directories:
  - $HOME/usr/local
warnings_are_errors: true
before_install:
  - curl -OL https://raw.githubusercontent.com/jefferis/nat/master/build-cmtk.sh
  - bash build-cmtk.sh
before_script:
  - export PATH=$PATH:$HOME/usr/local/bin
env:
  global:
    - RGL_USE_NULL=TRUE
